package com.nlt.mobileteam.wifidirect.controller;

public enum Message {

    MESSAGE_START,
    MESSAGE_STOP,
    MESSAGE_SYNC_RECORD_START,
    MESSAGE_DELETE_RECORDED,
    MESSAGE_PROJ_INFO,
    MESSAGE_SAVE_LOCAL,
    MESSAGE_ASSISTANT_DISCONNECTING,
    MESSAGE_DIRECTOR_DISCONNECTING,
    MESSAGE_OK_CLOSING,
    MESSAGE_REQUEST_VIDEO,
    MESSAGE_HEADER_SENDING_VIDEO,
    MESSAGE_CLOSE_DIALOGS,
    MESSAGE_GET_NEXT_VIDEO_PART,
    MESSAGE_ABORT_VIDEO_SENDING,
    MESSAGE_PART_OF_VIDEO_SENDING,
    MESSAGE_UUID,

    MESSAGE_READ,
    SWAP_HANDLER,
    NOTIFY_DEVICE_LIST,
    MESSAGE_UPD_TIMER_VIEW,

    MESSAGE_SONY_DISCONNECT,
    MESSAGE_SONY_RECONNECT,

    MESSAGE_GOPRO_NOT_CONNECTED,
    MESSAGE_GOPRO_NO_VIDEO_TO_SENT,
    MESSAGE_GOPRO_VIDEO_RECEIVE_ABORTED,

    MESSAGE_INIT_STREAMER,
    MESSAGE_MEDIA_FORMAT,
    MESSAGE_START_CINA_STREAM,
    MESSAGE_STOP_CINA_STREAM,
    MESSAGE_START_PEER_BROADCAST_SERVICE,
    MESSAGE_STOP_PEER_BROADCAST_SERVICE,
    MESSAGE_INIT_MEDIA_SOCKETS,
    MESSAGE_START_SOCIAL_STREAM,
    MESSAGE_STOP_SOCIAL_STREAM,
    MESSAGE_PING,
    MESSAGE_PONG,
    MESSAGE_OFF_AUDIO_STREAM,
    MESSAGE_ON_AUDIO_STREAM,
    MESSAGE_CAM_INIT_CONTROLS,
    MESSAGE_DIRECTOR_CHANGE_CONTROL,
    CONTROL_CHANGED,
    MESSAGE_CHAT_MESSAGE,
    MESSAGE_DIRECTOR_UPDATE_DEVICE_INFO;

    public static Message valueOfOrdinal(int ordinal) {
        return Message.values()[ordinal];
    }

    public static Message valueOfOrdinal(String ordinal) {
        return valueOfOrdinal(Integer.parseInt(ordinal));
    }

    @Override
    public String toString() {
        return String.valueOf(ordinal());
    }
}
